name: Create release of manifolds dataset

on: 
  workflow_dispatch:

jobs: 
  run-python: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          cache: 'pip'
      # Currently the only dependency required for the conversion, thus
      # saving us some time for running the action.
      - run: pip install numpy

      - name: Run conversion script
        run: | 
          sh scripts/convert_manifolds.sh

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Manifolds Dataset"
          prerelease: false
          files: |
            2_manifolds.json.gz
            3_manifolds.json.gz
