name: Create documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:3.5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install torch==2.2.0
          pip install numpy
          pip install git+https://github.com/Lezcano/geotorch/


      - name: Install mantra
        run: |
          pip install -e .

      - name: Install sphinx
        run: |
          sudo apt install pandoc
          pip install pypandoc
          pip install sphinx sphinx_rtd_theme myst_parser[linkify] nbsphinx


      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
