name: Create release for dataset

on: 
  workflow_dispatch:

jobs: 
  run-python: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10.11"

      - name: Install requirements
        run: | 
        python -m pip install -r requirements.txt
        python ./dataprocessing/process_manifolds.py  