name: Create dataset release

on: 
  workflow_dispatch:
  push: 
    tags:
      - "v*.*.*"

jobs: 
  run-python: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install Python and cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: pip install numpy

      - name: Run conversion script
        run: | 
          sh scripts/convert_manifolds.sh
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          make_latest: true
          files: |
            2_manifolds.json.gz
            3_manifolds.json.gz

