name: Python Linting
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install pylint
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Run Pylint
        run: pylint mantra 